[package]
name = "lucky_commit"
version = "1.0.2"
authors = ["Teddy Katz <teddy.katz@gmail.com>"]
description = "Make your git commits lucky!"
repository = "https://github.com/not-an-aardvark/lucky-commit"
license = "MIT"

[dependencies]

flate2 = "1.0"
num_cpus = "1.0"
rust-crypto = "^0.2"
