name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.57.0'
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose --no-default-features
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --no-default-features
    - name: Run tests
      run: cargo test --verbose --no-default-features
    - name: Run benchmark
      run: 'cargo build --release --no-default-features && time target/release/lucky_commit --benchmark'
